config/routes.rb
Rails.application.routes.draw do
  get 'users/new'

  root 'static_pages#home'
  
  get '/home', to:'static_pages#home'
  
  get '/kora', to:'static_pages#kora'

  get '/mazie', to:'static_pages#mazie'

  get '/together', to:'static_pages#together'

 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
  validates :animal, :path,  presence: true
  validates :animal, :path, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email = email.downcase }
    validates :name,  presence: true, length: { maximum: 50 }   
    VALID_EMAIL_REGEX =   /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
                      format: { with: VALID_EMAIL_REGEX },
                      uniqueness: { case_sensitive: false }
                      
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }
                      
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
    
    def new
    end
    
    def create
    end

    def destroy
    end
    
    def index
    end
    
    def show
    end
    
    def update
    end
    
    
    
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
  
  def kora
  end

  def mazie
  end

  def together
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
      <%= link_to "Kora and Mazie", root_path, id: "logo" %>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Kora", kora_path %></li>
        <li><%= link_to "Mazie", mazie_path %></li>
        <li><%= link_to "Together", together_path %></li>
      </ul>
    </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title></title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
<body>
  <div class="container">
    <%= render 'layouts/header' %>
    <%= yield %>
  </div>
</body>
</html>

app/views/static_pages/home.html.erb
<div>
    <div class="container-fluid">
        
        <div class="row row-centered">
            <div class="col-sm-4 col-centered">
              <h2>Kora</h2>
              
            </div>
            <div class="col-sm-4 col-centered">
              <h2>Mazie</h2>
            </div>
            <div class="col-sm-4 col-centered">
              <h2>Together</h2>
            </div>
        </div>
        
        <div class="row row-centered">
            <div class="col-sm-4 col-centered">
                
            </div>
            <div class="col-sm-4 col-centered">
                
            </div>
            <div class="col-sm-4 col-centered">
                
            </div>
        </div>
            
       
    </div>
</div>

app/views/static_pages/kora.html.erb
<h1>Kora</h1>
<p>This will be where pictures of Kora are</p>

app/views/static_pages/mazie.html.erb
<h1>Mazie</h1>
<p>This is where pictures of Mazie will go.</p>

app/views/static_pages/together.html.erb
<h1>Kora and Mazie Together</h1>
<p>This is where pictures of both the animals together will go.</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>